---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Yarn install
        run: yarn install
      - name: Add older eslint version
        run: |
          yarn add eslint@8.17.0 --exact
          yarn eslint --version
      - name: Yarn lint
        run: yarn lint
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: docker build -t agilbos/webapp:latest .
