---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Yarn install
        run: yarn install
      - name: Add older eslint version
        run: |
          yarn add eslint@8.17.0 --exact
          yarn eslint --version
      - name: Yarn lint
        run: yarn lint
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp:latest
      - name: Docker run
        run: docker run -dp 127.0.0.1:3000:3000 ${{ secrets.DOCKER_USERNAME }}/webapp:latest
      - name: Docker ps
        run: docker ps
      - name: netstat
        run: netstat -tuln
      - name: curl
        run: curl 127.0.0.1:3000
      - name: yarn test
        run: yarn test
